### ISSUE TITLE
论文中公式与描述不一致

### ISSUE THREAD

**Issue by K-Boss** [WhoTHU/Adversarial_camou#10]
![图片](https://github.com/user-attachments/assets/154cde54-9bfc-4d0d-9ac4-514f9a8529be)

作者您好，公式中表达的是 $1-\lambda$ 控制可训练部分，但是下面说 $\lambda$ 是控制可训练部分，代码中也是如此

https://github.com/WhoTHU/Adversarial_camou/blob/eb42f8b42524d1478707aa8f9c55ccf7dd358344/train.py#L447

请问是论文中这个公式有误，还是我的理解有误？

**Comment by WhoTHU** [comment]
您好，公式(6)确实有笔误，应该如下图所示。感谢您的细心阅读和指正，我们已更新了修正后的arxiv版本。
<img width="596" alt="image" src="https://github.com/user-attachments/assets/0535c4e5-3556-478b-889a-3b5b17309eac">
