### ISSUE TITLE
requirements问题

### ISSUE THREAD

**Issue by wang1528186571** [WhoTHU/Adversarial_camou#6]
作者您好，我在安装咱们的代码时候无法用pip和conda安装requirements，请问您是否可以从新做一个requirements上传，非常感谢！

**Comment by WhoTHU** [comment]
你好，如果无法安装的话请移步README.md安装requirements中的内容

**Comment by wang1528186571** [comment]
> 你好，如果无法安装的话请移步README.md安装requirements中的内容

非常感谢您的回复，那个requirements不可以PiP安装，我只能一个一个去输入，如果后面出一个可以PIP的就太好啦
