### ISSUE TITLE
我不能下载yolov3的权重

### ISSUE THREAD

**Issue by wang1528186571** [WhoTHU/Adversarial_camou#7]
按照说明里的./arch/weights/download_weights.sh下载时候显示
--2024-05-16 17:04:28--  https://pjreddie.com/media/files/yolov3.weights
正在解析主机 pjreddie.com (pjreddie.com)... 162.0.215.52
正在连接 pjreddie.com (pjreddie.com)|162.0.215.52|:443... 已连接。
已发出 HTTP 请求，正在等待回应...

恳请作者回应，谢谢

**Comment by WhoTHU** [comment]
这个也许是您网络的问题
